Learning Rails (Demo App)/config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles   # To include all routes of articles
end

Learning Rails (Demo App)/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

Learning Rails (Demo App)/app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  
  validates :title, presence: true, length: { minimum: 5, maximum: 15 }
  validates :description, presence: true, length: { minimum: 20, maximum: 150 }
end

Learning Rails (Demo App)/app/models/user.rb
class User < ApplicationRecord
  has_many :articles

  validates :username, presence: true,
                       uniqueness: { case_sensitive: false },
                       length: { minimum: 3, maximum: 25 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, presence: true,
                    uniqueness: { case_sensitive: false },
                    length: { maximum: 105 },
                    format: { with: VALID_EMAIL_REGEX }
end

Learning Rails (Demo App)/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Learning Rails (Demo App)/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def show
  end

  def index
    @articles = Article.all
  end
  
  def new
    @article = Article.new
  end
  
  def edit
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article was updated successfully."
      redirect_to @article
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def create
    @article = Article.new(article_params)
    @article.user = User.last                    # Temporary assignment of user to articles

    if @article.save
      flash[:notice] = "Article was created successfully."
      redirect_to @article
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def destroy
    @article.destroy

    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description)
  end

end

Learning Rails (Demo App)/app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end

    def about
    end
end

Learning Rails (Demo App)/app/helpers/application_helper.rb
module ApplicationHelper
end

Learning Rails (Demo App)/app/helpers/articles_helper.rb
module ArticlesHelper
end

Learning Rails (Demo App)/app/helpers/pages_helper.rb
module PagesHelper
end

Learning Rails (Demo App)/app/views/articles/_error.html.erb
<% if @article.errors.any? %>
  <h2>Following Errors occured:-</h2>
  <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

Learning Rails (Demo App)/app/views/articles/_form.html.erb
<%= render 'error' %>

<%= form_with(model: @article, local: true) do |f| %>
  <p>
    <%= f.label :title %><br/>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %><br/>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

Learning Rails (Demo App)/app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= render 'form' %>

<%= link_to 'Cancel and return to the articles listing', articles_path %>

Learning Rails (Demo App)/app/views/articles/index.html.erb
<h1>Articles listing page</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Written by</th>
      <th colspan = 3>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.description %></td>
        <td><%= article.user.username %></td>
        <td><%= link_to 'Show', article_path(article) %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Delete', article_path(article), method: :delete, data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<p>
  <%= link_to 'Create New Article', new_article_path %>
</p>

Learning Rails (Demo App)/app/views/articles/new.html.erb
<h1>Create a new article</h1>

<% if @article.errors.any? %>
  <h2>Following Errors occured:-</h2>
  <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with scope: :article, url: articles_path, local: true do |f| %>

  <p>
    <%= f.label :title %><br/>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %><br/>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Articles Listing', articles_path %>

Learning Rails (Demo App)/app/views/articles/show.html.erb
<h1>Showing article details</h1>

<p><strong>Title: </strong><%= @article.title %></p>
<p><strong>Description: </strong><%= @article.description %></p>
<p><strong>by </strong><%= @article.user.username %></p>

<%= link_to 'Edit', edit_article_path(@article) %> | 
<%= link_to 'Delete', article_path(@article), method: :delete, data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %></td> | 
<%= link_to 'Articles List', articles_path %>

Learning Rails (Demo App)/app/views/layouts/_message.html.erb
<% flash.each do |name, msg| %> 
  <p style="color: green"> Notice:
    <%= msg %> 
  </p>
<% end %>

Learning Rails (Demo App)/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LearningRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/message' %>
    <%= yield %>
  </body>
</html>

Learning Rails (Demo App)/app/views/pages/about.html.erb
<h2> This is the 'about' page </h2>
<p>
------------ We are working on Rails 7 --------------
Please read the documentation carefully
</p>


<%= link_to 'Home', root_path %> | 
<%= link_to 'Articles listing', articles_path %>

Learning Rails (Demo App)/app/views/pages/home.html.erb
<h1> Hello World! </h1>

<p><strong> This is the beginning of Rails. </strong></p>

<%= link_to 'Articles listing', articles_path %> | 
<%= link_to 'About', about_path %>